{% set name = "piconnect" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3fed11f542fd2ab99670d801a43774569b0885f388a0e0e5d5834196aacc7d2

build:
  number: 0
  skip: true  # [not win]
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pandas
    - python
    - pythonnet
    - pytz
    - wrapt

test:
  imports:
    - PIconnect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Hugovdberg/PIconnect
  summary: Python connector to OSIsoft PI SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hugovdberg
