{% set name = "piconnect" %}
{% set version = "0.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PIconnect-{{ version }}.tar.gz
  sha256: a910d5ad79598a95106d7202f062cf6ee0d9b87d6a6e0a937c2fdf1b10ba46f7

build:
  number: 1
  skip: true  # [not win]
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pandas
    - python
    - pythonnet
    - pytz
    - wrapt

test:
  imports:
    - PIconnect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Hugovdberg/PIconnect
  summary: Python connector to OSIsoft PI SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hugovdberg
