{% set name = "piconnect" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PIconnect-{{ version }}.tar.gz
  sha256: 7f1a4a7595c35be645150c2e8ace41b44e42725b22983228b6cc51e4395b9687

build:
  number: 1
  skip: true  # [not win]
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pandas
    - python
    - pythonnet
    - pytz
    - wrapt

test:
  imports:
    - PIconnect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Hugovdberg/PIconnect
  summary: Python connector to OSIsoft PI SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hugovdberg
